name: Build

on:
  push:
    branches: [ '**' ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - '.github/workflows/build.yml'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly

      - name: Enable nightly
        run: rustup override set nightly

      - name: Rust cache
        uses: Swatinem/rust-cache@v2.2.0

      - name: Build library
        run: cargo build --release
